// Generated by PixelCheck from hafsausmani.com (an owned site) on 2026-10-07.
export default function App() {
  return (
    <div data-pc="0" className="flow-root min-h-screen w-full font-sans bg-[#fff4e4]">
      <div data-pc="1" className="flex flex-col w-full min-h-[63px] md:min-h-[82px] xl:min-h-[114px]">
        <nav data-pc="2" data-seg="S1" className="flow-root w-full bg-transparent min-h-0 mt-[27px] md:mt-[36px] pt-[0px]">
          <div data-pc="3" className="w-full max-w-[264px] md:max-w-[352px] xl:max-w-[347px] mx-auto pl-[16px] pr-[16px]">
            <div data-pc="4" className="flex flex-row flex-wrap justify-center md:justify-between pl-0 md:pl-[0px] pr-0 md:pr-[0px] items-start mt-[0px] w-full">
              <a data-pc="5" href="#" className="text-[12px] md:text-[13px] text-[#1f1f1f] md:text-[#1e1e1e] xl:text-[#333230] font-medium md:font-semibold tracking-[0.126em] md:tracking-[0.15em] leading-none text-left no-underline max-w-full min-w-0 mt-[0px] ml-[0px] self-auto whitespace-nowrap">WORK</a>
              <a data-pc="6" href="#" className="text-[12px] md:text-[13px] text-[#2f2e2d] md:text-[#1a1a1a] xl:text-[#333230] font-normal md:font-semibold tracking-[0.15em] leading-none text-left no-underline max-w-full min-w-0 mt-[1px] md:mt-[0px] ml-[33px] md:ml-[0px] self-auto whitespace-nowrap">ABOUT</a>
              <a data-pc="7" href="#" className="text-[12px] md:text-[13px] text-[#343331] md:text-[#1a1a1a] xl:text-[#333230] font-normal md:font-medium xl:font-semibold tracking-[0.15em] leading-none text-left no-underline max-w-full min-w-0 mt-[1px] md:mt-[0px] ml-[34px] md:ml-[0px] self-auto whitespace-nowrap">CONTACT</a>
            </div>
          </div>
        </nav>
      </div>
      <div data-pc="8" data-seg="S2" className="flow-root w-full bg-transparent min-h-0 mt-[0px] pt-[0px]">
        <div data-pc="9" className="w-full max-w-none md:max-w-[96px] xl:max-w-[1280px] mx-0 md:mx-auto pl-[153px] md:pl-[16px] xl:pl-[502px] pr-[153px] md:pr-[16px] xl:pr-[502px]">
          <div data-pc="10" className="flex xl:hidden flex-row xl:flex-col flex-wrap xl:flex-nowrap justify-start pl-0 pr-0 items-start mt-[0px] w-full">
            <h1 data-pc="11" className="block xl:hidden text-[16px] text-[#373634] font-medium tracking-[0.15em] leading-none text-left no-underline max-w-full min-w-0 mt-[0px] xl:mt-0 ml-[0px] xl:ml-0 self-auto whitespace-nowrap">HELLO</h1>
          </div>
        </div>
      </div>
      <div data-pc="12" data-seg="S3" className="flow-root w-full relative bg-transparent min-h-0 mt-[109px] md:mt-[32px] xl:mt-[0px] pt-[0px]">
        <div data-pc="13" className="w-full max-w-[265px] md:max-w-[543px] xl:max-w-[797px] mx-auto pl-[16px] pr-[16px]">
          <div data-pc="14" className="flex xl:hidden flex-row xl:flex-col flex-wrap xl:flex-nowrap justify-start pl-0 pr-0 items-start mt-[0px] w-full">
            <h1 data-pc="15" className="block xl:hidden text-[70px] md:text-[151px] xl:text-[70px] text-[#191919] font-bold tracking-[-0.014em] md:tracking-normal xl:tracking-[-0.014em] leading-none text-left no-underline max-w-full min-w-0 mt-[0px] xl:mt-0 ml-[0px] xl:ml-0 self-auto whitespace-nowrap">HAFSA</h1>
          </div>
        </div>
        <div data-pc="16" aria-hidden="true" className="block xl:hidden absolute left-1/2 -translate-x-1/2 top-[58px] md:top-[112px] xl:top-[329px] w-[200px] md:w-[360px] xl:w-[420px] h-[200px] md:h-[360px] xl:h-[420px] bg-[#d4d4d8] border-0 rounded-[24px] md:rounded-[28px] xl:rounded-[31px] shadow-[0_54px_56px_rgba(0,0,0,0.14)] md:shadow-[0_40px_76px_rgba(0,0,0,0.15)]" />
      </div>
      <div data-pc="17" data-seg="S4" className="flow-root w-full bg-transparent min-h-0 mt-[179px] md:mt-[279px] xl:mt-[0px] pt-[0px]">
        <div data-pc="18" className="w-full max-w-[306px] md:max-w-[629px] xl:max-w-[931px] mx-auto pl-[16px] pr-[16px]">
          <div data-pc="19" className="flex xl:hidden flex-row xl:flex-col flex-wrap xl:flex-nowrap justify-start pl-0 pr-0 items-start mt-[0px] w-full">
            <h1 data-pc="20" className="block xl:hidden text-[70px] md:text-[152px] xl:text-[70px] text-[#171717] md:text-[#181818] xl:text-[#171717] font-bold tracking-[-0.01em] md:tracking-[-0.012em] xl:tracking-[-0.01em] leading-none text-left no-underline max-w-full min-w-0 mt-[0px] xl:mt-0 ml-[0px] xl:ml-0 self-auto whitespace-nowrap">USMANI</h1>
          </div>
        </div>
      </div>
      <div data-pc="21" data-seg="S5" className="flow-root w-full bg-transparent min-h-0 mt-[112px] md:mt-[40px] xl:mt-[0px] pt-[0px]">
        <div data-pc="22" className="w-full max-w-none md:max-w-[396px] xl:max-w-[1280px] mx-0 md:mx-auto pl-[36px] md:pl-[16px] xl:pl-[118px] pr-[36px] md:pr-[16px] xl:pr-[118px]">
          <div data-pc="23" className="flex xl:hidden flex-row xl:flex-col flex-wrap xl:flex-nowrap justify-end md:justify-start pl-0 pr-[0px] md:pr-0 items-start mt-[0px] w-full">
            <p data-pc="24" className="block xl:hidden text-[13px] md:text-[14px] xl:text-[13px] text-[#7c7870] md:text-[#7f7a73] xl:text-[#7c7870] font-normal md:font-medium xl:font-normal tracking-[0.063em] md:tracking-[0.114em] xl:tracking-[0.063em] leading-tight text-left no-underline max-w-[314px] md:max-w-[364px] xl:max-w-[314px] min-w-0 mt-[0px] xl:mt-0 ml-[0px] xl:ml-0 self-auto">Product Designer · San Francisco Bay Area</p>
          </div>
        </div>
      </div>
      <div data-pc="25" data-seg="S6" className="flow-root w-full bg-transparent min-h-0 mt-[26px] md:mt-[36px] xl:mt-[0px] pt-[0px]">
        <div data-pc="26" className="w-full max-w-[235px] xl:max-w-[698px] mx-auto pl-[16px] pr-[16px]">
          <div data-pc="27" className="flex xl:hidden flex-row xl:flex-col flex-wrap xl:flex-nowrap justify-start pl-0 pr-0 items-start mt-[0px] w-full">
            <button data-pc="28" type="button" className="flex xl:hidden w-full xl:w-[203px] max-w-full h-[54px] bg-[#1a1a1a] md:bg-[#191919] xl:bg-[#1a1a1a] border-0 rounded-[27px] shadow-none items-center gap-[8px] shrink-0 justify-center px-[12px] cursor-pointer text-left mt-[0px] xl:mt-0 ml-[0px] xl:ml-0 self-auto">
              <span data-pc="29" className="block xl:hidden text-[13px] md:text-[15px] xl:text-[13px] text-[#fff4e4] font-semibold tracking-[0.138em] md:tracking-[0.077em] xl:tracking-[0.138em] leading-none text-left no-underline max-w-full min-w-0 whitespace-nowrap">SEE MY WORK</span>
              <div data-pc="30" aria-hidden="true" className="w-[16px] max-w-full h-[10px] bg-[#f7ecdc] border-0 rounded-none shadow-none shrink-0" />
              <div data-pc="31" aria-hidden="true" className="w-[16px] max-w-full h-[16px] bg-[#d4d4d8] border-0 rounded-none shadow-none shrink-0" />
            </button>
          </div>
        </div>
      </div>
      <header data-pc="32" data-seg="S7" className="flow-root w-full relative bg-transparent min-h-0 mt-[0px] pt-[0px]">
        <div data-pc="33" className="w-full max-w-none xl:max-w-[1280px] mx-0 xl:mx-auto pl-[27px] md:pl-[55px] xl:pl-[91px] pr-[27px] md:pr-[55px] xl:pr-[91px]">
          <div data-pc="34" className="hidden xl:flex flex-col xl:flex-row flex-nowrap xl:flex-wrap justify-start xl:justify-center pl-0 pr-0 items-start mt-[0px] w-full">
            <h1 data-pc="35" className="hidden xl:block text-[278px] text-[#1a1a1a] font-bold tracking-[-0.009em] leading-none text-left no-underline max-w-full min-w-0 mt-0 xl:mt-[0px] ml-0 xl:ml-[0px] self-auto whitespace-nowrap">HAFSA</h1>
          </div>
          <div data-pc="36" className="hidden xl:flex flex-col flex-nowrap justify-start pl-0 pr-0 items-start mt-[0px] xl:mt-[273px] w-full">
            <h1 data-pc="37" className="hidden xl:block text-[272px] text-[#1a1a1a] font-bold tracking-normal leading-none text-left no-underline max-w-full min-w-0 mt-0 xl:mt-[0px] ml-0 xl:ml-[6px] self-auto xl:self-start whitespace-nowrap">USMANI</h1>
            <div data-pc="38" aria-hidden="true" className="hidden xl:block w-[91px] max-w-full h-[38px] bg-[#171717] border-0 rounded-none shadow-none shrink-0 mt-0 xl:mt-[0px] ml-0 xl:ml-[386px] self-auto xl:self-start" />
          </div>
        </div>
        <div data-pc="39" aria-hidden="true" className="hidden xl:block absolute left-1/2 -translate-x-1/2 top-[246px] md:top-[242px] xl:top-[215px] w-[200px] md:w-[360px] xl:w-[420px] h-[200px] md:h-[360px] xl:h-[420px] bg-[#d4d4d8] border-0 rounded-[24px] md:rounded-[28px] xl:rounded-[31px] shadow-[0_54px_56px_rgba(0,0,0,0.14)] md:shadow-[0_40px_76px_rgba(0,0,0,0.15)]" />
      </header>
    </div>
  );
}
