import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { fetchAssetBytes, projectEntries, projectFiles, projectZipName, sanitizeId, type ProjectMeta } from './project';
import { zipStore } from './zip';
import { PREVIEW_CDN } from './previewDoc';

const code = `// Generated by PixelCheck — run abc\nimport { useState } from "react";\nexport default function App() {\n  const [o, setO] = useState(false);\n  return <div className="font-sans p-4">Hi</div>;\n}\n`;
const meta: ProjectMeta = {
  id: 'Netflix signin_scaf2/120344',
  title: 'Sign-in page (dev capture)',
  source: 'three design frames',
  match: 92.15,
  scores: [
    { name: 'mobile', width: 390, score: 94.03 },
    { name: 'tablet', width: 768, score: 92.15 },
    { name: 'desktop', width: 1280, score: 97.46 },
  ],
  created: Date.UTC(2026, 9, 1, 20, 31) / 1000,
};
const files = projectFiles(code, meta);
const get = (p: string) => {
  const f = files.find((x) => x.path === p);
  if (!f) throw new Error(`missing ${p}`);
  return f.content;
};

describe('sanitizeId / zip name', () => {
  it('makes a valid npm package name fragment', () => {
    expect(sanitizeId('Netflix signin_scaf2/120344')).toBe('netflix-signin-scaf2-120344');
    expect(sanitizeId('--A..B--')).toBe('a-b');
    expect(sanitizeId('')).toBe('app');
    expect(sanitizeId('x'.repeat(300)).length).toBeLessThanOrEqual(200);
  });
  it('names the archive pixelcheck-<id>.zip', () => {
    expect(projectZipName('abl-plan-lambda-203138')).toBe('pixelcheck-abl-plan-lambda-203138.zip');
  });
});

describe('projectFiles', () => {
  it('has exactly the files of a runnable Vite project', () => {
    expect(files.map((f) => f.path).sort()).toEqual(
      ['.gitignore', 'README.md', 'index.html', 'package.json', 'postcss.config.js', 'src/App.jsx', 'src/index.css', 'src/main.jsx', 'tailwind.config.js', 'vite.config.js'].sort(),
    );
  });
  it('src/App.jsx is the generated code byte for byte', () => {
    expect(get('src/App.jsx')).toBe(code);
  });
  it('package.json: name, scripts and pinned deps', () => {
    const pkg = JSON.parse(get('package.json'));
    expect(pkg.name).toBe('pixelcheck-netflix-signin-scaf2-120344');
    expect(pkg.private).toBe(true);
    expect(pkg.type).toBe('module');
    expect(pkg.scripts).toEqual({ dev: 'vite', build: 'vite build', preview: 'vite preview' });
    expect(pkg.dependencies).toEqual({ react: '18.3.1', 'react-dom': '18.3.1' });
    expect(pkg.devDependencies).toEqual({ vite: '^6.0.0', '@vitejs/plugin-react': '^4.3.4', tailwindcss: '3.4.17', postcss: '^8.4.49', autoprefixer: '^10.4.20' });
  });
  it('tailwind.config.js matches the sandbox renderer (sandbox/render.mjs) and nothing else', () => {
    const tw = get('tailwind.config.js');
    expect(tw).toContain("content: ['./index.html', './src/**/*.{js,jsx}']");
    expect(tw).toContain("fontFamily: { sans: ['Inter', 'sans-serif'], mono: ['IBM Plex Mono', 'monospace'] }");
    expect(tw).toContain('plugins: []');
    expect(tw).not.toMatch(/darkMode|screens|colors/);
  });
  it('vite + postcss configs', () => {
    expect(get('vite.config.js')).toContain("import react from '@vitejs/plugin-react'");
    expect(get('vite.config.js')).toContain('plugins: [react()]');
    expect(get('postcss.config.js')).toContain('tailwindcss: {}');
    expect(get('postcss.config.js')).toContain('autoprefixer: {}');
  });
  it('index.html loads the verified fonts (same as the in-app preview) and the entry', () => {
    const html = get('index.html');
    expect(html).toContain(`href="${PREVIEW_CDN.fonts}"`);
    expect(PREVIEW_CDN.fonts).toContain('Inter:wght@400;500;600;700');
    expect(PREVIEW_CDN.fonts).toContain('IBM+Plex+Mono:wght@400;500');
    expect(html).toContain('<div id="root"></div>');
    expect(html).toContain('<script type="module" src="/src/main.jsx"></script>');
    expect(html).toContain('<title>Sign-in page (dev capture)</title>');
  });
  it('escapes the title in index.html', () => {
    const h = projectFiles(code, { ...meta, title: 'A <b> & "c"' }).find((f) => f.path === 'index.html')!.content;
    expect(h).toContain('<title>A &lt;b&gt; &amp; &quot;c&quot;</title>');
  });
  it('main.jsx + index.css', () => {
    const m = get('src/main.jsx');
    expect(m).toContain("import { StrictMode } from 'react'");
    expect(m).toContain("import { createRoot } from 'react-dom/client'");
    expect(m).toContain("import App from './App.jsx'");
    expect(m).toContain("import './index.css'");
    expect(m).toContain("createRoot(document.getElementById('root'))");
    const css = get('src/index.css');
    expect(css).toMatch(/@tailwind base;\s*@tailwind components;\s*@tailwind utilities;/);
  });
  it('README: source, scores, date, how to run, honest notes', () => {
    const r = get('README.md');
    expect(r).toContain('# Sign-in page (dev capture)');
    expect(r).toContain('Generated by PixelCheck from three design frames');
    expect(r).toContain('`Netflix signin_scaf2/120344`');
    expect(r).toContain('2026-10-01');
    expect(r).toMatch(/\| Mobile \| 390 px \| 94\.0 \|/);
    expect(r).toMatch(/\| Desktop \| 1280 px \| 97\.5 \|/);
    expect(r).toContain('Match (worst breakpoint): **92.2**');
    expect(r).toContain('npm install');
    expect(r).toContain('npm run dev');
    expect(r).toMatch(/placeholder/i);
    expect(r).toContain('Inter');
    expect(r).toContain('IBM Plex Mono');
  });
  it('README copes with missing scores', () => {
    const r = projectFiles(code, { ...meta, match: null, scores: [] }).find((f) => f.path === 'README.md')!.content;
    expect(r).not.toContain('Match (worst breakpoint)');
    expect(r).toContain('npm run dev');
  });
  it('.gitignore', () => {
    expect(get('.gitignore').split('\n')).toEqual(expect.arrayContaining(['node_modules', 'dist']));
  });
});

// ------------------------------------------------------------------------------------------------ owned sites

const HA = 'd'.repeat(64);
const HB = 'e'.repeat(64);
const delivered = `export default function App() {\n  return <img data-pc="1" src="/assets/${HA}.png" alt="Hero" className="w-full block object-cover" />;\n}\n`;
const pngBytes = new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0, 255, 13, 10]);
const svgBytes = new TextEncoder().encode('<svg xmlns="http://www.w3.org/2000/svg"/>');
const ok = async (rel: string) => (rel.endsWith('.png') ? pngBytes : svgBytes);

describe('projectFiles images notes', () => {
  const readme = (images?: 'placeholder' | 'own' | 'fallback') => projectFiles(code, meta, images).find((f) => f.path === 'README.md')!.content;
  it('default (no owned images) is unchanged: placeholder note', () => {
    expect(readme()).toBe(readme('placeholder'));
    expect(readme()).toMatch(/Images are placeholders/);
    expect(readme()).not.toMatch(/your site's own|could not be downloaded/i);
  });
  it('own: one line saying the images are the site\'s own, in public/assets/', () => {
    const r = readme('own');
    expect(r).not.toMatch(/Images are placeholders/);
    const lines = r.split('\n').filter((l) => /site's own/i.test(l));
    expect(lines).toHaveLength(1);
    expect(lines[0]).toContain('public/assets/');
  });
  it('fallback: says the images could not be downloaded and the code is as scored', () => {
    const r = readme('fallback');
    const lines = r.split('\n').filter((l) => /could not be downloaded/i.test(l));
    expect(lines).toHaveLength(1);
    expect(lines[0]).toMatch(/as scored/i);
  });
});

describe('projectEntries', () => {
  it('without delivered code: exactly the plain project (runs without owned images are unchanged)', async () => {
    const fetchAsset = async () => {
      throw new Error('must not fetch');
    };
    const out = await projectEntries({ scored: code, delivered: null, assets: [], meta, fetchAsset });
    expect(out.images).toBe('placeholder');
    expect(out.entries).toEqual(projectFiles(code, meta).map((f) => ({ path: f.path, data: f.content })));
  });

  it('with delivered code: src/App.jsx is the delivered code and every asset is stored under public/assets/', async () => {
    const asked: string[] = [];
    const out = await projectEntries({
      scored: code,
      delivered,
      assets: [`assets/${HA}.png`, `assets/${HB}.svg`],
      meta,
      fetchAsset: async (rel) => {
        asked.push(rel);
        return ok(rel);
      },
    });
    expect(out.images).toBe('own');
    expect(asked.sort()).toEqual([`assets/${HA}.png`, `assets/${HB}.svg`]);
    const byPath = new Map(out.entries.map((e) => [e.path, e.data]));
    expect(byPath.get('src/App.jsx')).toBe(delivered);
    expect(byPath.get(`public/assets/${HA}.png`)).toEqual(pngBytes);
    expect(byPath.get(`public/assets/${HB}.svg`)).toEqual(svgBytes);
    expect(String(byPath.get('README.md'))).toMatch(/site's own/);
  });

  it('skips asset paths that are not assets/<64hex>.<ext>', async () => {
    const asked: string[] = [];
    const out = await projectEntries({
      scored: code,
      delivered,
      assets: [`assets/${HA}.png`, '../../etc/passwd', `assets/${HB}.html`],
      meta,
      fetchAsset: async (rel) => {
        asked.push(rel);
        return pngBytes;
      },
    });
    expect(asked).toEqual([`assets/${HA}.png`]);
    expect(out.entries.filter((e) => e.path.startsWith('public/')).map((e) => e.path)).toEqual([`public/assets/${HA}.png`]);
  });

  it('any failed asset → the whole zip falls back to the scored code, no assets, README says so', async () => {
    const out = await projectEntries({
      scored: code,
      delivered,
      assets: [`assets/${HA}.png`, `assets/${HB}.svg`],
      meta,
      fetchAsset: async (rel) => {
        if (rel.endsWith('.svg')) throw new Error('404');
        return pngBytes;
      },
    });
    expect(out.images).toBe('fallback');
    const byPath = new Map(out.entries.map((e) => [e.path, e.data]));
    expect(byPath.get('src/App.jsx')).toBe(code);
    expect(out.entries.some((e) => e.path.startsWith('public/'))).toBe(false);
    expect(String(byPath.get('README.md'))).toMatch(/could not be downloaded/);
  });

  it('an empty asset body counts as a failure', async () => {
    const out = await projectEntries({ scored: code, delivered, assets: [`assets/${HA}.png`], meta, fetchAsset: async () => new Uint8Array() });
    expect(out.images).toBe('fallback');
  });

  it('delivered code with no listed assets still ships the delivered code', async () => {
    const out = await projectEntries({ scored: code, delivered, assets: [], meta, fetchAsset: ok });
    expect(out.images).toBe('own');
    expect(out.entries.find((e) => e.path === 'src/App.jsx')!.data).toBe(delivered);
  });

  it('the zip round-trips the binary asset', async () => {
    const out = await projectEntries({ scored: code, delivered, assets: [`assets/${HA}.png`], meta, fetchAsset: ok });
    const z = zipStore(out.entries);
    const dir = mkdtempSync(join(tmpdir(), 'pc-proj-'));
    writeFileSync(join(dir, 'p.zip'), z);
    expect(execFileSync('unzip', ['-p', join(dir, 'p.zip'), `public/assets/${HA}.png`]).equals(Buffer.from(pngBytes))).toBe(true);
  });
});

describe('fetchAssetBytes', () => {
  const res = (status: number, type: string, body: Uint8Array) =>
    ({ ok: status >= 200 && status < 300, status, headers: { get: (k: string) => (k.toLowerCase() === 'content-type' ? type : null) }, arrayBuffer: async () => body.buffer.slice(body.byteOffset, body.byteOffset + body.byteLength) }) as unknown as Response;
  it('returns the bytes of an image response', async () => {
    expect(await fetchAssetBytes('u', async () => res(200, 'image/png', pngBytes))).toEqual(pngBytes);
  });
  it('throws on HTTP errors', async () => {
    await expect(fetchAssetBytes('u', async () => res(404, 'text/plain', svgBytes))).rejects.toThrow();
  });
  it('throws on an HTML body (dev-server SPA fallback for a missing file)', async () => {
    await expect(fetchAssetBytes('u', async () => res(200, 'text/html; charset=utf-8', svgBytes))).rejects.toThrow();
  });
  it('throws on an empty body', async () => {
    await expect(fetchAssetBytes('u', async () => res(200, 'image/png', new Uint8Array()))).rejects.toThrow();
  });
});
