// A runnable Vite + React + Tailwind project around one generated App.jsx (zipped in the browser, lib/zip.ts).
// The Tailwind setup mirrors how the sandbox renderer built and scored the code (sandbox/render.mjs): the same
// content scope, fontFamily sans = Inter, mono = IBM Plex Mono, nothing else; fonts as in the in-app preview.
import { PREVIEW_CDN } from './previewDoc';
import { fmtScore } from './score';

export interface ProjectMeta {
  id: string;
  title: string;
  /** Where the design came from, e.g. "three design frames" or "a capture of example.com". */
  source?: string | null;
  /** The run's Match (= worst breakpoint). */
  match?: number | null;
  scores?: { name: string; width: number; score: number | null | undefined }[];
  /** unix seconds */
  created: number;
}

export interface ProjectFile {
  path: string;
  content: string;
}

/** npm-safe name fragment: lowercase, [a-z0-9-], no leading/trailing/double dashes, ≤ 200 chars. */
export function sanitizeId(id: string): string {
  const s = id
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 200)
    .replace(/-+$/g, '');
  return s || 'app';
}

export function projectZipName(id: string): string {
  return `pixelcheck-${sanitizeId(id)}.zip`;
}

const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
const isoDate = (unix: number) => new Date(unix * 1000).toISOString().slice(0, 10);

export function projectFiles(code: string, meta: ProjectMeta): ProjectFile[] {
  const name = `pixelcheck-${sanitizeId(meta.id)}`;
  const pkg = {
    name,
    private: true,
    version: '0.0.0',
    type: 'module',
    scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
    dependencies: { react: '18.3.1', 'react-dom': '18.3.1' },
    devDependencies: { vite: '^6.0.0', '@vitejs/plugin-react': '^4.3.4', tailwindcss: '3.4.17', postcss: '^8.4.49', autoprefixer: '^10.4.20' },
  };

  const scores = (meta.scores ?? []).filter((s) => s.score != null);
  const readme = [
    `# ${meta.title}`,
    '',
    `Generated by PixelCheck from ${meta.source || 'design frames'} — run \`${meta.id}\`, ${isoDate(meta.created)}.`,
    '',
    'One responsive React + Tailwind file (`src/App.jsx`), exactly as PixelCheck rendered and scored it in a Token Factory Sandbox.',
    '',
    ...(scores.length
      ? [
          '## Match scores (from the run)',
          '',
          '| Breakpoint | Width | Score |',
          '| --- | --- | --- |',
          ...scores.map((s) => `| ${cap(s.name)} | ${s.width} px | ${fmtScore(s.score)} |`),
          '',
          ...(meta.match != null ? [`Match (worst breakpoint): **${fmtScore(meta.match)}** / 100`, ''] : []),
        ]
      : []),
    '## Run it',
    '',
    '```sh',
    'npm install',
    'npm run dev',
    '```',
    '',
    '`npm run build` writes a static site to `dist/`.',
    '',
    '## Notes',
    '',
    '- Images are placeholders (plain blocks) — PixelCheck rebuilds layout, colours and text, not image content.',
    '- Fonts are Inter and IBM Plex Mono from Google Fonts: the fonts the code was verified with.',
    '- `tailwind.config.js` matches the PixelCheck sandbox renderer (same content scope and font families), so the',
    '  page builds the same way it was scored. Small differences in font rasterisation between browsers are normal.',
    '',
  ].join('\n');

  return [
    { path: 'package.json', content: JSON.stringify(pkg, null, 2) + '\n' },
    {
      path: 'vite.config.js',
      content: `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({\n  plugins: [react()],\n});\n`,
    },
    { path: 'postcss.config.js', content: `export default {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {},\n  },\n};\n` },
    {
      path: 'tailwind.config.js',
      content:
        `/** @type {import('tailwindcss').Config} */\n// Same as the PixelCheck sandbox renderer that scored src/App.jsx.\nexport default {\n` +
        `  content: ['./index.html', './src/**/*.{js,jsx}'],\n` +
        `  theme: {\n    extend: {\n      fontFamily: { sans: ['Inter', 'sans-serif'], mono: ['IBM Plex Mono', 'monospace'] },\n    },\n  },\n` +
        `  plugins: [],\n};\n`,
    },
    {
      path: 'index.html',
      content:
        `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n` +
        `    <title>${esc(meta.title)}</title>\n` +
        `    <link rel="preconnect" href="https://fonts.googleapis.com" />\n    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />\n` +
        `    <link rel="stylesheet" href="${PREVIEW_CDN.fonts}" />\n  </head>\n  <body>\n    <div id="root"></div>\n` +
        `    <script type="module" src="/src/main.jsx"></script>\n  </body>\n</html>\n`,
    },
    {
      path: 'src/main.jsx',
      content:
        `import { StrictMode } from 'react';\nimport { createRoot } from 'react-dom/client';\nimport App from './App.jsx';\nimport './index.css';\n\n` +
        `createRoot(document.getElementById('root')).render(\n  <StrictMode>\n    <App />\n  </StrictMode>,\n);\n`,
    },
    {
      path: 'src/index.css',
      content:
        `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n` +
        `/* as in the PixelCheck renderer */\nbody {\n  margin: 0;\n  font-family: 'Inter', sans-serif;\n  -webkit-font-smoothing: antialiased;\n}\n`,
    },
    { path: 'src/App.jsx', content: code },
    { path: 'README.md', content: readme },
    { path: '.gitignore', content: 'node_modules\ndist\n' },
  ];
}

/** Fallback widths when a bundle does not list its breakpoints. */
export const BREAKPOINT_WIDTH: Record<string, number> = { mobile: 390, tablet: 768, desktop: 1280 };
