import { describe, expect, it } from 'vitest';
import { projectFiles, projectZipName, sanitizeId, type ProjectMeta } from './project';
import { PREVIEW_CDN } from './previewDoc';

const code = `// Generated by PixelCheck — run abc\nimport { useState } from "react";\nexport default function App() {\n  const [o, setO] = useState(false);\n  return <div className="font-sans p-4">Hi</div>;\n}\n`;
const meta: ProjectMeta = {
  id: 'Netflix signin_scaf2/120344',
  title: 'Sign-in page (dev capture)',
  source: 'three design frames',
  match: 92.15,
  scores: [
    { name: 'mobile', width: 390, score: 94.03 },
    { name: 'tablet', width: 768, score: 92.15 },
    { name: 'desktop', width: 1280, score: 97.46 },
  ],
  created: Date.UTC(2026, 9, 1, 20, 31) / 1000,
};
const files = projectFiles(code, meta);
const get = (p: string) => {
  const f = files.find((x) => x.path === p);
  if (!f) throw new Error(`missing ${p}`);
  return f.content;
};

describe('sanitizeId / zip name', () => {
  it('makes a valid npm package name fragment', () => {
    expect(sanitizeId('Netflix signin_scaf2/120344')).toBe('netflix-signin-scaf2-120344');
    expect(sanitizeId('--A..B--')).toBe('a-b');
    expect(sanitizeId('')).toBe('app');
    expect(sanitizeId('x'.repeat(300)).length).toBeLessThanOrEqual(200);
  });
  it('names the archive pixelcheck-<id>.zip', () => {
    expect(projectZipName('abl-plan-lambda-203138')).toBe('pixelcheck-abl-plan-lambda-203138.zip');
  });
});

describe('projectFiles', () => {
  it('has exactly the files of a runnable Vite project', () => {
    expect(files.map((f) => f.path).sort()).toEqual(
      ['.gitignore', 'README.md', 'index.html', 'package.json', 'postcss.config.js', 'src/App.jsx', 'src/index.css', 'src/main.jsx', 'tailwind.config.js', 'vite.config.js'].sort(),
    );
  });
  it('src/App.jsx is the generated code byte for byte', () => {
    expect(get('src/App.jsx')).toBe(code);
  });
  it('package.json: name, scripts and pinned deps', () => {
    const pkg = JSON.parse(get('package.json'));
    expect(pkg.name).toBe('pixelcheck-netflix-signin-scaf2-120344');
    expect(pkg.private).toBe(true);
    expect(pkg.type).toBe('module');
    expect(pkg.scripts).toEqual({ dev: 'vite', build: 'vite build', preview: 'vite preview' });
    expect(pkg.dependencies).toEqual({ react: '18.3.1', 'react-dom': '18.3.1' });
    expect(pkg.devDependencies).toEqual({ vite: '^6.0.0', '@vitejs/plugin-react': '^4.3.4', tailwindcss: '3.4.17', postcss: '^8.4.49', autoprefixer: '^10.4.20' });
  });
  it('tailwind.config.js matches the sandbox renderer (sandbox/render.mjs) and nothing else', () => {
    const tw = get('tailwind.config.js');
    expect(tw).toContain("content: ['./index.html', './src/**/*.{js,jsx}']");
    expect(tw).toContain("fontFamily: { sans: ['Inter', 'sans-serif'], mono: ['IBM Plex Mono', 'monospace'] }");
    expect(tw).toContain('plugins: []');
    expect(tw).not.toMatch(/darkMode|screens|colors/);
  });
  it('vite + postcss configs', () => {
    expect(get('vite.config.js')).toContain("import react from '@vitejs/plugin-react'");
    expect(get('vite.config.js')).toContain('plugins: [react()]');
    expect(get('postcss.config.js')).toContain('tailwindcss: {}');
    expect(get('postcss.config.js')).toContain('autoprefixer: {}');
  });
  it('index.html loads the verified fonts (same as the in-app preview) and the entry', () => {
    const html = get('index.html');
    expect(html).toContain(`href="${PREVIEW_CDN.fonts}"`);
    expect(PREVIEW_CDN.fonts).toContain('Inter:wght@400;500;600;700');
    expect(PREVIEW_CDN.fonts).toContain('IBM+Plex+Mono:wght@400;500');
    expect(html).toContain('<div id="root"></div>');
    expect(html).toContain('<script type="module" src="/src/main.jsx"></script>');
    expect(html).toContain('<title>Sign-in page (dev capture)</title>');
  });
  it('escapes the title in index.html', () => {
    const h = projectFiles(code, { ...meta, title: 'A <b> & "c"' }).find((f) => f.path === 'index.html')!.content;
    expect(h).toContain('<title>A &lt;b&gt; &amp; &quot;c&quot;</title>');
  });
  it('main.jsx + index.css', () => {
    const m = get('src/main.jsx');
    expect(m).toContain("import { StrictMode } from 'react'");
    expect(m).toContain("import { createRoot } from 'react-dom/client'");
    expect(m).toContain("import App from './App.jsx'");
    expect(m).toContain("import './index.css'");
    expect(m).toContain("createRoot(document.getElementById('root'))");
    const css = get('src/index.css');
    expect(css).toMatch(/@tailwind base;\s*@tailwind components;\s*@tailwind utilities;/);
  });
  it('README: source, scores, date, how to run, honest notes', () => {
    const r = get('README.md');
    expect(r).toContain('# Sign-in page (dev capture)');
    expect(r).toContain('Generated by PixelCheck from three design frames');
    expect(r).toContain('`Netflix signin_scaf2/120344`');
    expect(r).toContain('2026-10-01');
    expect(r).toMatch(/\| Mobile \| 390 px \| 94\.0 \|/);
    expect(r).toMatch(/\| Desktop \| 1280 px \| 97\.5 \|/);
    expect(r).toContain('Match (worst breakpoint): **92.2**');
    expect(r).toContain('npm install');
    expect(r).toContain('npm run dev');
    expect(r).toMatch(/placeholder/i);
    expect(r).toContain('Inter');
    expect(r).toContain('IBM Plex Mono');
  });
  it('README copes with missing scores', () => {
    const r = projectFiles(code, { ...meta, match: null, scores: [] }).find((f) => f.path === 'README.md')!.content;
    expect(r).not.toContain('Match (worst breakpoint)');
    expect(r).toContain('npm run dev');
  });
  it('.gitignore', () => {
    expect(get('.gitignore').split('\n')).toEqual(expect.arrayContaining(['node_modules', 'dist']));
  });
});
