// A runnable Vite + React + Tailwind project around one generated App.jsx (zipped in the browser, lib/zip.ts).
// The Tailwind setup mirrors how the sandbox renderer built and scored the code (sandbox/render.mjs): the same
// content scope, fontFamily sans = Inter, mono = IBM Plex Mono, nothing else; fonts as in the in-app preview.
import { PREVIEW_CDN } from './previewDoc';
import { fmtScore } from './score';
import { ASSET_RE } from './owned';
import type { ZipEntry } from './zip';

export interface ProjectMeta {
  id: string;
  title: string;
  /** Where the design came from, e.g. "three design frames" or "a capture of example.com". */
  source?: string | null;
  /** The run's Match (= worst breakpoint). */
  match?: number | null;
  scores?: { name: string; width: number; score: number | null | undefined }[];
  /** unix seconds */
  created: number;
}

export interface ProjectFile {
  path: string;
  content: string;
}

/** npm-safe name fragment: lowercase, [a-z0-9-], no leading/trailing/double dashes, ≤ 200 chars. */
export function sanitizeId(id: string): string {
  const s = id
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 200)
    .replace(/-+$/g, '');
  return s || 'app';
}

export function projectZipName(id: string): string {
  return `pixelcheck-${sanitizeId(id)}.zip`;
}

const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
const isoDate = (unix: number) => new Date(unix * 1000).toISOString().slice(0, 10);

/** What the zip does with images: grey placeholders (every run without owned images), the site's own images under
 * public/assets/, or placeholders because those images could not be downloaded. */
export type ImagesMode = 'placeholder' | 'own' | 'fallback';

const IMAGES_NOTE: Record<ImagesMode, string> = {
  placeholder: '- Images are placeholders (plain blocks) — PixelCheck rebuilds layout, colours and text, not image content.',
  own: "- Images are your site's own, in `public/assets/` — PixelCheck scored the layout with grey blocks in their place.",
  fallback: '- Images are placeholders (plain blocks): your site\'s images could not be downloaded, so this is the code as scored.',
};

export function projectFiles(code: string, meta: ProjectMeta, images: ImagesMode = 'placeholder'): ProjectFile[] {
  const name = `pixelcheck-${sanitizeId(meta.id)}`;
  const pkg = {
    name,
    private: true,
    version: '0.0.0',
    type: 'module',
    scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
    dependencies: { react: '18.3.1', 'react-dom': '18.3.1' },
    devDependencies: { vite: '^6.0.0', '@vitejs/plugin-react': '^4.3.4', tailwindcss: '3.4.17', postcss: '^8.4.49', autoprefixer: '^10.4.20' },
  };

  const scores = (meta.scores ?? []).filter((s) => s.score != null);
  const readme = [
    `# ${meta.title}`,
    '',
    `Generated by PixelCheck from ${meta.source || 'design frames'} — run \`${meta.id}\`, ${isoDate(meta.created)}.`,
    '',
    'One responsive React + Tailwind file (`src/App.jsx`), exactly as PixelCheck rendered and scored it in a Token Factory Sandbox.',
    '',
    ...(scores.length
      ? [
          '## Match scores (from the run)',
          '',
          '| Breakpoint | Width | Score |',
          '| --- | --- | --- |',
          ...scores.map((s) => `| ${cap(s.name)} | ${s.width} px | ${fmtScore(s.score)} |`),
          '',
          ...(meta.match != null ? [`Match (worst breakpoint): **${fmtScore(meta.match)}** / 100`, ''] : []),
        ]
      : []),
    '## Run it',
    '',
    '```sh',
    'npm install',
    'npm run dev',
    '```',
    '',
    '`npm run build` writes a static site to `dist/`.',
    '',
    '## Notes',
    '',
    IMAGES_NOTE[images],
    '- Fonts are Inter and IBM Plex Mono from Google Fonts: the fonts the code was verified with.',
    '- `tailwind.config.js` matches the PixelCheck sandbox renderer (same content scope and font families), so the',
    '  page builds the same way it was scored. Small differences in font rasterisation between browsers are normal.',
    '',
  ].join('\n');

  return [
    { path: 'package.json', content: JSON.stringify(pkg, null, 2) + '\n' },
    {
      path: 'vite.config.js',
      content: `import { defineConfig } from 'vite';\nimport react from '@vitejs/plugin-react';\n\nexport default defineConfig({\n  plugins: [react()],\n});\n`,
    },
    { path: 'postcss.config.js', content: `export default {\n  plugins: {\n    tailwindcss: {},\n    autoprefixer: {},\n  },\n};\n` },
    {
      path: 'tailwind.config.js',
      content:
        `/** @type {import('tailwindcss').Config} */\n// Same as the PixelCheck sandbox renderer that scored src/App.jsx.\nexport default {\n` +
        `  content: ['./index.html', './src/**/*.{js,jsx}'],\n` +
        `  theme: {\n    extend: {\n      fontFamily: { sans: ['Inter', 'sans-serif'], mono: ['IBM Plex Mono', 'monospace'] },\n    },\n  },\n` +
        `  plugins: [],\n};\n`,
    },
    {
      path: 'index.html',
      content:
        `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n` +
        `    <title>${esc(meta.title)}</title>\n` +
        `    <link rel="preconnect" href="https://fonts.googleapis.com" />\n    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />\n` +
        `    <link rel="stylesheet" href="${PREVIEW_CDN.fonts}" />\n  </head>\n  <body>\n    <div id="root"></div>\n` +
        `    <script type="module" src="/src/main.jsx"></script>\n  </body>\n</html>\n`,
    },
    {
      path: 'src/main.jsx',
      content:
        `import { StrictMode } from 'react';\nimport { createRoot } from 'react-dom/client';\nimport App from './App.jsx';\nimport './index.css';\n\n` +
        `createRoot(document.getElementById('root')).render(\n  <StrictMode>\n    <App />\n  </StrictMode>,\n);\n`,
    },
    {
      path: 'src/index.css',
      content:
        `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n` +
        `/* as in the PixelCheck renderer */\nbody {\n  margin: 0;\n  font-family: 'Inter', sans-serif;\n  -webkit-font-smoothing: antialiased;\n}\n`,
    },
    { path: 'src/App.jsx', content: code },
    { path: 'README.md', content: readme },
    { path: '.gitignore', content: 'node_modules\ndist\n' },
  ];
}

/** Fetch one bundle asset as bytes. Rejects HTTP errors, empty bodies and HTML (a dev server's SPA fallback). */
export async function fetchAssetBytes(url: string, fetchImpl: (u: string) => Promise<Response> = (u) => fetch(u)): Promise<Uint8Array> {
  const res = await fetchImpl(url);
  if (!res.ok) throw new Error(`${res.status} — ${url}`);
  if (/text\/html/i.test(res.headers.get('content-type') ?? '')) throw new Error(`not an image — ${url}`);
  const bytes = new Uint8Array(await res.arrayBuffer());
  if (!bytes.length) throw new Error(`empty — ${url}`);
  return bytes;
}

/** Zip entries for the project. With delivered code (owned site) every asset is fetched into public/assets/ — Vite serves
 * public/ at the root, so `/assets/x.png` works unchanged. If any asset fails, the whole zip falls back to the scored code. */
export async function projectEntries(input: {
  scored: string;
  delivered: string | null;
  assets: string[];
  meta: ProjectMeta;
  fetchAsset: (rel: string) => Promise<Uint8Array>;
}): Promise<{ entries: ZipEntry[]; images: ImagesMode }> {
  const plain = (code: string, images: ImagesMode, extra: ZipEntry[] = []) => ({
    entries: [...projectFiles(code, input.meta, images).map((f) => ({ path: f.path, data: f.content })), ...extra],
    images,
  });
  if (!input.delivered) return plain(input.scored, 'placeholder');
  const rels = [...new Set(input.assets.filter((a) => ASSET_RE.test(a)))];
  try {
    const files = await Promise.all(
      rels.map(async (rel) => {
        const data = await input.fetchAsset(rel);
        if (!data?.length) throw new Error(`empty — ${rel}`);
        return { path: `public/${rel}`, data };
      }),
    );
    return plain(input.delivered, 'own', files);
  } catch {
    return plain(input.scored, 'fallback');
  }
}

/** Fallback widths when a bundle does not list its breakpoints. */
export const BREAKPOINT_WIDTH: Record<string, number> = { mobile: 390, tablet: 768, desktop: 1280 };
